spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login-app # so heisst unser client
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/local #mein Realm heisst local. Allgemein eignet es sich, fuer verschiedene Umgebungen verschiedene Realms zu bauen. Local heisst das ding jetzt, weil ichs so benannt hab - dev soll auch zugreifen
            user-name-attribute: preferred_username
